version: '3.8'
services:
  uberanalysis:
    build: .
    image: dylalva/uberanalysis:latest
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./models:/app/models:ro
      - ./uploads:/app/uploads
      - ./predictions.db:/app/predictions.db
    env_file:
      - .env
    restart: unless-stopped