version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ../models:/app/models
      - ./predictions.db:/app/predictions.db
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
